name: Neutron
version: ${project.version}
main: net.saifs.neutron.Neutron
api-version: 1.13
authors: [Saif]
website: github.com/saifsuleman
commands:
  neutron:
    description: Neutron Command
  balance:
    aliases: bal
  shop:
    aliases: neutronshop