name: MasonPlugin
version: ${project.version}
main: net.saifs.masonplugin.MasonPlugin
api-version: 1.13
authors: [Saif]
website: github.com/saifsuleman
commands:
  mason:
    description: Mason Command